### ISSUE TITLE
SolutionCollapseError should be a warning 

### ISSUE THREAD

**Issue by MDCHAMP** [MDCHAMP/FreeLunch#27]
Simple fix required.

**Comment by TimothyRogers** [comment]
Can I recommend that we randomly perturb all the solutions as well as raise the warning otherwise the lack of diversity in the population will cause issues in the next generation.

**Comment by MDCHAMP** [comment]
Yeah that sounds like a good idea. We can mention that this is happening in the warning message.

**Comment by MDCHAMP** [comment]
`KrillSingularityWarning`

**Comment by MDCHAMP** [comment]
Closed by #37
